config/routes.rb
Rails.application.routes.draw do
  resources :deportes do
    collection { post :import }
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/help/relations', to: 'static_pages#help_relations'
  get '/help/avatar', to: 'static_pages#help_avatar'
  get '/help/opciones', to: 'static_pages#help_opciones'
  get '/about', to: 'static_pages#about'
  get '/acceso', to: 'users#new'
  post '/acceso', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    collection { post :import }
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :categorias do
    collection { post :import }
  end
  get '/equipos/forma_rep'
  post '/equipos/reporte_asist', to: 'equipos#reporte_asist', as: 'reporte_asist'
  resources :players do
    collection { post :import }
  end
  get '/eventos/forma_prog' # Get programming parameters form
  get '/eventos/calendario' => 'eventos#calendario', as: 'calendario'
  post '/eventos/programa'   => 'eventos#programa',   as: 'programa'
  get '/eventos/form_borrar' # Get borrar parameters form
  post '/eventos/borrar'    =>'eventos#borra',   as: 'borrar'
  resources :eventos
  get '/equipos/:id/eventos_feed' => 'equipos#eventos_feed', as: 'eventosFeed'
  get '/eventos/:id/players_feed' => 'eventos#evento_players', as: 'eventoPlayers'
  # asistencias#new not required because Asistencia.new is called at
  # eventos#evento_players
  # get '/asistencias/new', to: 'asistencias#new'
  post '/asistencias', to: 'asistencias#create'
  get '/validar/:equipo_id', to: 'players#validar'
	resources :equipos do
	  collection { post :import }
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def help_relations
    #code
  end

  def help_avatar
    #code
  end

  def help_opciones
    #code
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "Autor") %>
    <h1>Acerca de mí</h1>
    <p>
      Esta aplicación fue desarrollada por:<br>
      <%= image_tag "tarjeta.jpg" %>
    </p>

app/views/static_pages/help.html.erb
<% provide(:title, "Ayuda") %>
    <h1>Ayuda</h1>
    <% if current_user.admin? %>
      <table class="ayuda",style="text-align:left;">
        <thead>
          <tr>
            <th>Sección</th>
            <th>Descripción</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= link_to "Avatar", help_avatar_path %></td>
            <td>La foto de su perfil se administra en la aplicación Gravatar.com; para que aparezca su foto deberá crear una cuenta en esta aplicación.</td>
          </tr>
          <tr>
            <td><%= link_to "Relaciones", help_relations_path %></td>
            <td>Explica la forma en que las tablas de la base de datos se relacionan entre si y las consideraciones que afectan el sistema.</td>
          </tr>
          <tr>
            <td><%= link_to "Opciones", help_opciones_path %></td>
            <td>Explica las opciones que presenta el menu principal presentado en la barra superior de la aplicación.</td>
          </tr>
        </tbody>
      </table>
    <% else %>
    <table>
      <thead>
        <tr>
          <th>Sección</th>
          <th>Descripción</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= link_to "Avatar", help_avatar_path %></td>
          <td>La foto de su perfil se administra en la aplicación Gravatar.com; para que aparezca su foto deberá crear una cuenta en esta aplicación.</td>
        </tr>
        <tr>
          <td colspan="2">Opciones del menú principal</td>
        </tr>
        <tr>
          <td>Inicio</td>
          <td>Esta opción lo lleva a la pantalla donde verá la lista de equipos que están a su cargo. Haciendo click en el nombre de alguno de los equipos le mostrará una tabla con la lista de eventos activos del equipo, podrá ver tanto eventos ya registrados como eventos por registrar, la diferencia es el ícono en la columna 'Activar'.</td>
        </tr>
        <tr>
          <td>Ayuda</td>
          <td>Podrá acceder a esta página.</td>
        </tr>
        <tr>
          <td>Cuenta</td>
          <td>Esta opción le presenta un menú con tres opciones: Perfil, Modificar Datos y Salir de Sesión.</td>
        </tr>
        <tr>
          <td>Perfil</td>
          <td>Esta opción le mostrará sus datos (avatar, email y teléfono) así como la lista de equipos que tiene asignados. Haciendo click sobre el nombre de cualquier equipo le mostrará los detalles del equipo (nombre, deporte, rama, categoría) y la lista de alumnos/jugadores registrados.</td>
        </tr>
        <tr>
          <td>Modificar Datos</td>
          <td>Esta opción mostrará una forma para modificar o simplemente ver sus datos personales (Nombre, email, teléfono) y le permitirá modificar su contraseña. No es necesario teclear la contraseña si no quiere cambiarla, si quiere cambiar la contraseña deberá escribirla dos veces para verificar que no hay errores de escritura.</td>
        </tr>
        <tr>
          <td>Salir de Sesión</td>
          <td>Esta opción terminará su sesión con la aplicación.</td>
        </tr>
      </tbody>
    </table>
    <% end %>

app/views/static_pages/help_avatar.html.erb
<div class="row">
  <div>
    <h2>Como crear su avatar</h2>
  </div>
  <table class="ayuda">
    <tr>
      <td>1.-</td>
      <td>Gravatar.com</td>
      <td>Haga click en el siguiente link: <a href="https://en.gravatar.com/">Gravatar.com</a> para ir al sitio de Gravatar.</td>
    </tr>
    <tr>
      <td>2.-</td>
      <td>Crear cuenta</td>
      <td>Una vez en el sitio de Gravatar haga click en el botón que dice [Create Your Own Gravatar].</td>
    </tr>
    <tr>
      <td>3.-</td>
      <td>Proporcione sus datos</td>
      <td>Escriba el correo electrónico que utiliza con esta aplicación en el campo 'E-mail Address'. <br>A continuación escriba un nombre de usuario mayor de 4 caractéres, incluyendo números y letras en el campo 'Username', este será su nombre de usuario para Gravatar.com.<br> Ahora escriba una clave contraseña de su elección en el campo 'Password'. </td>
    </tr>
    <tr>
      <td>4.-</td>
      <td>Crear cuenta</td>
      <td>Por último haga click en el botón [Sign up ->] para acceder a la aplicación.</td>
    </tr>
    <tr>
      <td>5.-</td>
      <td>Correo de confirmación</td>
      <td>Recibirá un correo de confirmación por parte de Worpress.com con una liga para acceder a su cuenta de gravatar, esta es un botón que dice: [Activate Account], haga click en este botón.</td>
    </tr>
    <tr>
      <td>6.-</td>
      <td>Sign up to gravatar</td>
      <td>El link anterior lo llevará a un sitio donde podrá encontrar un botón que dice [Sign up to Gravatar] o [Iniciar sesión en Gravatar] haga click sobre este.</td>
    </tr>
    <tr>
      <td>7.-</td>
      <td>Entrar en la aplicación</td>
      <td>Proporcione los datos que introdujo en el paso 3.</td>
    </tr>
    <tr>
      <td>8.-</td>
      <td>Añadir foto</td>
      <td>Aparecerá un mensaje diciendo que no tiene definida ninguna imagen para su correo electrónico, haga click en el link que dice 'Añadir uno haciendo click aquí'.</td>
    </tr>
    <tr>
      <td>9.-</td>
      <td>Cargar imagen</td>
      <td>Haga click en el cuadro que dice 'Cargar nuevo' con una imagen de un folder.</td>
    </tr>
    <tr>
      <td>10.-</td>
      <td>Añadir una imagen nueva</td>
      <td>Haga click en el botón que dice 'Seleccionar archivo', ahora podrá buscar su foto en su PC o su dispositivo móbil. El nombre dely haga click en el botón [Siguiente]</td>
    </tr>
    <tr>
      <td>11.-</td>
      <td>Finalizar</td>
      <td>Haga click en el botón que dice [Crop and Finish] o [Cultivos y acabado] y listo!</td>
    </tr>
  </table>
</div>

app/views/static_pages/help_opciones.html.erb
<% provide(:title, "Ayuda") %>
<div class="row">
  <div>
    <h2>Opciones del menú principal</h2>
  </div>
  <table>
    <tr>
      <td colspan="2">Estas opciones solo se presentan a usuarios con privilegios de administrador (de izquierda a derecha).</td>
    </tr>
    <tr>
      <td>Inicio</td>
      <td>Esta opción le mostrará la familiar vista de sus datos con su propio avatar (si ha definido ya uno) junto con la lista de los equipos que tiene asignados, haciendo click sobre un equipo le mostrará LA LISTA DE EVENTOS DEFINIDOS PARA ESE EQUIPO en particular.<br> Siendo usted un administrador solo podrá ver los eventos de los equipos en la vista de calendario (opción 'Herramientas' -> 'Calendario').
      </td>
    </tr>
    <tr>
      <td>Ayuda</td>
      <td>Esta misma página.</td>
    </tr>
    <tr>
      <td>Usuarios</td>
      <td>Esta opción le mostrará la lista de usuarios de la aplicación, administradores y entrenadores, con sus datos personales y la lista de equipos que tiene asignados. SI hace click sobre el nombre de los equipos podrá ver los detalles del equipo con la lista de alumnos/jugadores.<br>Al inicio de la lista está el botón [Registrar Usuario] con el que podrá dar de alta ususarios nuevos.<br>De igual manera, junto al nombre de cada usuario encontrará una liga para eliminar el registro de cada usuario, si usted hace click en 'Eliminar' el sistema le preguntará si está seguro, si usted está seguro y elimina un usuario NO HAY FORMA DE RECUPERAR EL REGISTRO de manera que si quiere recuperar el registro del usuario deberá crearlo de nueva cuenta.<br>Si usted hace click sobre el nombre de algún equipo asignado al usuario podrá ver los detalles del equipo y la lista de jugadores asignados.</td>
    </tr>
    <tr>
      <td>Mantenimiento</td>
      <td>Esta opción le mostrará la lista de elementos que conforman esta aplicación: Deportes, Categorías, Equipos, Jugadores y Eventos.<br>Haciendo click en estas opciones le mostrará el listado de elementos registrados, jungto con los mecanismos para crear, eliminar, importar y exportar archivos a Excel y en formato CSV (Comma Separated Values ó Valores separados por comas).</td>
    </tr>
    <tr>
      <td> </td>
      <td>Elementos:</td>
    </tr>
    <tr>
      <td> </td>
      <td>
        <table>
          <tr>
            <td>Deportes</td>
            <td>Cada equipo practica un deporte específico y solo uno, esta es una lista simple y puede ser administrada.</td>
          </tr>
          <tr>
            <td>Categorías</td>
            <td>Cada equipo pertenece a una categoría definida, esta opción le permite crear, modificar y eliminar categorías circunscritas dentro de un rango de fechas.<br>EL rango de fechas se utiliza para validar la edad de los jugadores inscritos en el equipo.</td>
          </tr>
          <tr>
            <td>Equipos</td>
            <td>Este elemento es el centro de la aplicación, todos los alumnos pertenecen a un equipo y los eventos se programan por equipos. Esta opción le permite administrar (crear, modificar, eliminar, exportar e importar) registros de equipos, vea la descripción de dependencias <a href=help_relations_path>aquí</a> para una descripción detallada. </td>
          </tr>
          <tr>
            <td>Jugadores</td>
            <td>Con esta opción usted podrá crear registros de jugadores y tendrá la capacidad de modificar y eliminar registros además podrá importar listas enteras de jugadores así como exportarlos a Excel.</td>
          </tr>
          <tr>
            <td>Eventos</td>
            <td>Es en esta opción donde usted podrá crear, modificar y eliminar eventos para los equipos, estos eventos son cualquier actividad que usted necesite controlar asistencias. EL entrenador del equipo podrá ver los eventos creados aquí en la lista de eventos para cada equipo.</td>
          </tr>
        </table>
      </td>
    </tr>
    <tr>
      <td>Herramientas</td>
      <td>Esta opción da acceso a las herramientas principales para la administración de la aplicación: Calendario y Reporte de asistencias por Entrenador.</td>
    </tr>
    <tr>
      <td> </td>
      <td>Elementos:</td>
    </tr>
    <tr>
      <td> </td>
      <td>
        <table>
          <tr>
            <td>Calendario</td>
            <td>Esta opción le mostrará un formato de calendario mensual con la lista de eventos programados en cada día, mostrando el nombre del equipo y el tipo de evento abreviado: Ent, Jgo, etc. Haciendo click sobre el evento usted podrá ver la lista de asistencia de jugadores para ese evento, EN caso de que no exista todavía una definición por parte del entrenador verá la leyenda 'Nuevo Ingreso', en caso contrario podrá ver la asistencia de cada jugador.</td>
          </tr>
          <tr>
            <td>Reporte</td>
            <td>Esta opción le ayudará a definir los parámetros para generar un reporte de asistencia por entrenador, usted deberá definir el entrenador y el rango de fechas (inicial y final) para que el sistema seleccione los eventos que se registraron dentro de ese lapso.</td>
          </tr>
        </table>
      </td>
    </tr>
    <tr>
      <td>Cuenta</td>
      <td>Esta opción le permite gestionar los elementos de su propia cuenta, Perfil, Modificar Datos y Salir de Sesión.</td>
    </tr>
    <tr>
      <td> </td>
      <td>Elementos:</td>
    </tr>
    <tr>
      <td> </td>
      <td>
        <table>
          <tr>
            <td>Perfil</td>
            <td>Esta opción le mostrará sus datos personales y si tiene usted equipos asignados como entrenador aparecerá la lista de estos equipos, haciendo click en alguno de estos equipos podrá ver los detalles del equipo y la lista de jugadores inscritos en él.</td>
          </tr>
          <tr>
            <td>Modificar Datos</td>
            <td>Esta opción le permitirá verificar y modificar sus datos personales como Nombre, Email, Teléfono y podrá también cambiar su contraseña.<br>Para cambiar su contraseña deberá escribir al menos 8 caractéres alfanuméricos (letras y números) en el campo 'Password' y DEBERÁ REPETIR LA MISMA PALABRA en el campo 'Confirmación'.<br>Podrá usted también designar Administradores de la aplicación checando el recuadro que se encuentra bajo el campo confirmación.<br>Al final de la página se encuentra su imagen de avatar, si hace click en el link 'cambiar', será redirigido al sitio Gravatar.com donde podrá usted cambiar su imagen de avatar.</td>
          </tr>
          <tr>
            <td>Salir de Sesión</td>
            <td>COn esta opción da usted por terminada la sesión con la aplicación y vuelve a la pantalla de inicio de sesión.<br>Le recomiendo que si usted se va a ausentar de su estación de trabajo salga de la sesión para evitar que otra persona encuentre la sesión activa y pueda hacer mal uso de la aplicación.</td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</div>

app/views/static_pages/help_relations.html.erb
<% provide(:title, "Ayuda") %>
<div class="row">
    <div>
      <h2>Consideraciones para la base de datos</h2>
    </div>
  <table class="ayuda">
    <tr>
      <td colspan="2">Orden lógico y secuencia de dependencias de la base de datos</td>
    </tr>
    <tr>
      <td colspan="2">A continuación se presenta la lista de tablas que conforman la base de datos de la aplicación. Esta lista está ordenada de la tabla más simple a la más compleja, es decir, la primera tabla no tiene dependencias pero la siguente depende de la primera, es decir, que los registros o renglones de la segunda tabla están relacionados con alguno de los renglones de la anterior, de tal manera que si se elimina un renglón de la tabla anterior tendremos una situación de falta de integridad de la base de datos.</td>
    </tr>
    <tr>
      <th class="col-left">Tabla</th>
      <th>Recordar</th>
    </tr>
    <tr>
      <td class="col-left">Deportes</td>
      <td>
        <span>
          Esta es la tabla más simple pero la tabla de equipos depende de ella. Cuando borre un elemento, los equipos relacionados podrán estar en error. Asegurese de modificar la columna de deporte para los equipos afectados antes de borrar un elemento de la tabla.
        </span><br>
        <span>
          En caso de que realmente requiera eliminar un elemento de la tabla Deportes, haga primero la modificación al registro de la tabla de Equipos, cambiando a otro deporte o al registro especial 'INDETERMINADO'.
        </span>
      </td>
    </tr>
    <tr>
      <td class="col-left">Categorías</td>
      <td>
        <span>
          Al igual que con la tabla de Deportes, los elementos de la tabla de Equipos depende de algún elemento de esta tabla, ante de borrar una categoría, verifique que los equipos que pertenecen a la categoría que será eliminada son asignados a otra categoría, esto implica que deberá crear la nueva categoría si esta no existe.
        </span><br>
        <span>
          Si desea eliminar una categoría, deberá primero modificar el registro de Equipo que pertenece a la categoría asignandole otra categoría, esto implica que deberá crear la nueva categoría primero y luego hacer el cambio de categoría en el equipo. En caso de que no tenga claro que categoría deberá usar para el Equipo, asigne la categoría especial 'NO DEFINIDA'.
        </span>
      </td>
    </tr>
    <tr>
      <td class="col-left">Entrenadores/Usuarios</td>
      <td>
        <span>
          Tanto entrenadores como administradores están registrados en la tabla de Usuarios en la base de datos. El registro de entrenador deberá existir antes de poder asignarle los equipos que tendrá a su cargo. Por este motivo el administrador deberá asegurarse en caso de desear eliminar un entrenador, que él o los equipos que están asignados al entrenador por eliminar, sean asignados a otro entrenador antes de eliminar a aquél.
        </span>
        <span>
          Para eliminar un entrenador sin afectar las dependencias de equipos, asegúrese de que cambie el entrenador del equipo por el nuevo entrenador primero, si el nuevo entrenador no tiene registro todavía, deberá crear primero el registro del entrenador y luego hacer el cambio en el equipo ó si no está definido el entrenador nuevo y de todos modos quiere eliminar el registro del entrenador saliente asigne el equipo al registro especial 'NO DETERMINADO'.
        </span>
      </td>
    </tr>
    <tr>
      <td class="col-left">Equipos</td>
      <td>
        <span>
          Los alumnos/jugadores deben pertenecer a un equipo para que su registro tenga integridad en la base de datos y para poder fundamentar las estadísticas que son el objetivo de esta aplicación, por lo cual el administrador deberá asegurarse que los jugadores estén asignados a un equipo en todos momento, esto es; si usted va a eliminar un equipo asegúrese que antes de eliminarlo los jugadores que están asignados a este sean asignados a otro equipo. Por este motivo los equipos deben existir antes de asignar a los jugadores.
        </span>
        <span>
          En caso de requerir eliminar un equipo y aún no tener definidas las características del nuevo equipo al que serán asignados los jugadores, el administrador podrá asignar a los jugadores al registro especial de equipos 'POR DEFINIR' y proceder entonces a borrar el registro de equipo no deseado, pero recuerde: Antes de borrar un equipo hay que cambiar la asignación de equipo en el registro de TODOS los jugadores afectados.
        </span>
      </td>
    </tr>
    <tr>
      <td class="col-left">Jugadores</td>
      <td>
        <span>
          La tabla de jugadores está libre de dependencias críticas y usted podrá eliminar jugadores sin problema. Aún cuando cada registro de jugador contiene una referencia a un equipo, la relación no implica riesgo para la integridad de la base de datos.
        </span>
      </td>
    </tr>
  </table>
</div>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-xs-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
    </aside>
  </div>

<% else %>
  <div class="center jumbotron">
    <div id="row-cont-jumbo">
      <div id="left-jumbo">
        <h1>Formando Campeones</h1>
      </div>
      <div id="right-jumbo">
        <%= image_tag "castor.gif",  size: "100x70" %>
      </div>
    </div>
    <h2>
      Administración de
      <strong>Deportes</strong>
    </h2>

</div>
<% end %>