config/routes.rb
Rails.application.routes.draw do
  resources :deportes do
    collection { post :import }
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/help/relations', to: 'static_pages#help_relations'
  get '/help/avatar', to: 'static_pages#help_avatar'
  get '/help/opciones', to: 'static_pages#help_opciones'
  get '/about', to: 'static_pages#about'
  get '/acceso', to: 'users#new'
  post '/acceso', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    collection { post :import }
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :categorias do
    collection { post :import }
  end
  get '/equipos/forma_rep'
  post '/equipos/reporte_asist', to: 'equipos#reporte_asist', as: 'reporte_asist'
  resources :players do
    collection { post :import }
  end
  get '/eventos/forma_prog' # Get programming parameters form
  get '/eventos/calendario' => 'eventos#calendario', as: 'calendario'
  post '/eventos/programa'   => 'eventos#programa',   as: 'programa'
  get '/eventos/form_borrar' # Get borrar parameters form
  post '/eventos/borrar'    =>'eventos#borra',   as: 'borrar'
  resources :eventos
  get '/equipos/:id/eventos_feed' => 'equipos#eventos_feed', as: 'eventosFeed'
  get '/eventos/:id/players_feed' => 'eventos#evento_players', as: 'eventoPlayers'
  # asistencias#new not required because Asistencia.new is called at
  # eventos#evento_players
  # get '/asistencias/new', to: 'asistencias#new'
  post '/asistencias', to: 'asistencias#create'
  get '/validar/:equipo_id', to: 'players#validar'
	resources :equipos do
	  collection { post :import }
	end
end

app/models/evento.rb
class Evento < ApplicationRecord
  belongs_to :equipo
  has_many :asistencias, dependent: :destroy
  accepts_nested_attributes_for :asistencias
	scope :done, -> { where(registrado: true) }
  # has_many :players, through: :asistencias
  # has_many :players, through: :equipo
  # accepts_nested_attributes_for :players
  validates :equipo_id, :fecha, :tipoEvento, presence: true

  # set alias for simple calendar format
  def start_time
    self.fecha
  end

  # Convert column data to comma separated values
  def self.to_csv(options = {})
    desired_columns = ["fecha", "tipoEvento", "equipo_id", "comment", "registrado"]
    CSV.generate(options) do |csv|
      csv << desired_columns
      all.each do |evento|
        csv << evento.attributes.values_at(*desired_columns)
      end
    end
  end
  
end

app/controllers/eventos_controller.rb
class EventosController < ApplicationController
  before_action :logged_in_user,  only: [:index, :edit, :update, :create, :destroy]
  before_action :set_evento,      only: [:show, :edit, :update, :destroy]
  before_action :set_equipos,     only: [:show, :new, :edit, :create, :update]
  before_action :set_tiposEvento,  only: [:new, :edit, :create, :update, :evento_players]

  # GET /eventos
  def index
    @eventos = Evento.paginate(page: params[:page])

    respond_to do |format|
      format.html
      format.csv { send_data @eventos.to_csv }
      format.xls
    end
  end

  # GET /eventos/calendario
  def calendario
    @user = current_user
    @eventos = Evento.all
  end

  # GET /eventos/1
  def show
		@user = current_user
    @equipo = @evento.equipo
    @jugadores = @equipo.players
    # @asistencias = @evento.asistencias
  end

  # GET /eventos/new
  def new
    @evento = Evento.new
  end

  # GET /eventos/1/edit
  def edit
  end

  # POST /eventos
  def create
    @evento = Evento.new(evento_params)

    if @evento.save
      flash[:success] = "Se insertó exitosamente el evento."
      redirect_to eventos_path
    else
      render 'new'
    end
  end

  # GET /eventos/:id/players as: :eventoPlayers
  def evento_players
    @evento = Evento.find(params[:id])
    @equipo = Equipo.find(@evento.equipo_id)
    @jugadores = @equipo.players
    p @jugadores
    @tiposAsistencia = ['asistió', 'falta', 'retardo', 'médico']

    @jugadores.each { |n| @evento.asistencias.build(player_id:n.id) }

  end

  # PATCH/PUT /eventos/1
  def update

    if @evento.update(evento_params)
      flash[:success] = "Se actualizó exitosamente el evento."
      redirect_to root_path
    else
      render 'edit'
    end
  end

  # DELETE /eventos/1
  def destroy
    @evento.destroy
    flash[:success] = "Se eliminó exitosamente el evento."
    redirect_to eventos_url
  end


  # GET /eventos/forma_prog
  def forma_prog
    @entrenadores = User.all
    @dias = %w[Dom Lun Mar Mie Jue Vie Sab]
    @evento = Evento.new
  end

  # POST /eventos/programa
  def programa
    entrenador = User.find(params[:entrenador])
    inicio = Date.parse(params[:inicio])
    final = Date.parse(params[:final])
    dias = params[:dias].map! {|ele| ele.to_i }
    @tipoEvento = "Entrenamiento"

    entrenador.equipos.each do |equipo|
      for @fecha in (inicio..final) do
        if dias.include?(@fecha.wday)
          @equipo_id = equipo.id
          @evento = Evento.new(parametros_evento)
          if !@evento.save
            flash[:error] = "No ha sido posible crear los eventos."
            redirect_to root_path
          else
            flash[:success] = "Se han creado exitosamente los eventos."
          end
        end
      end
    end
    redirect_to eventos_path
  end

  # GET /eventos/form_borrar
  def form_borrar

  end

  # POST /eventos/borrar
  def borra
    inicio = Date.parse(params[:inicio])
    final = Date.parse(params[:final])
    even = Evento.where("fecha > '#{inicio}' AND fecha < '#{final}'")
    even.destroy_all
    flash[:success] = "Se eliminaron exitosamente los eventos."
    redirect_to eventos_url
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_evento
      @evento = Evento.find(params[:id])
    end

    # Set options to select from forms
    def set_equipos
      @equipos = Equipo.all
    end

    def set_tiposEvento
      @tiposEvento = ['Entrenamiento', 'Partido', 'Topes', 'Competencia', 'Ligas']
    end

    # Never trust big bad internet, always use strong params
    def evento_params
      params.require(:evento).permit(:fecha, :tipoEvento, :equipo_id, :comment, :registrado, :asistencias_attributes => [:evento_id, :player_id, :tipo, :comment])
    end

    # Alternate parameter assemble
    def parametros_evento
      evento = { :fecha => @fecha,
                  :tipoEvento => @tipoEvento,
                  :equipo_id => @equipo_id,
                  :comment => "",
                  :registrado => false
                }
    end
end

app/helpers/eventos_helper.rb
module EventosHelper
  
end

app/views/eventos/_evento.html.erb
<tr id="evento-<%= evento.id %>">
  <td class="col-left"><%= evento.fecha.to_date %></td>
  <td class="col-left"><%= evento.tipoEvento %></td>
  <td class="col-left"><%= Equipo.find_by(id: evento.equipo_id).name %></td>
  <td class="col-left"><%= evento.comment %></td>
  <td><%= link_to '', edit_evento_path(evento), class: "glyphicon glyphicon-edit" %></td>
  <td><%= link_to '', evento, class: "glyphicon glyphicon-trash", method: :delete,
                      data: { confirm: '¿Es correcta la opción de borrar el evento?' } %></td>
</tr>

app/views/eventos/_form.html.erb
<div class="col-sm-6 col-sm-offset-3">
  <%= form_for(@evento) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <div>
      <%= f.label :fecha %>
      <%= f.date_field :fecha, :placeholder => "Fecha del evento", class: 'form-control' %>
    </div>
    <div>
      <%= f.label :tipoEvento %>
      <%= f.select :tipoEvento, @tiposEvento, :placeholder => "Entrenamiento o Juego",
                      class: 'form-control'%>
    </div>
    <div>
      <%= f.label :equipo_id %>
      <%= f.collection_select( :equipo_id, @equipos, :id, :name,
                  :placeholder => "Equipo que tendrá el evento", class: 'form-control') %>
    </div>

    <div>
      <%= f.label :comment %>
      <%= f.text_field :comment, :placeholder => "Comentario", class: 'form-control' %>
    </div>

    <%= f.submit "Guardar", class: "btn btn-default" %>
  <% end %>
</div>

app/views/eventos/calendario.html.erb
<div class="col-sm-8">
  <% if @user.admin? %>
    <h3>Eventos (<%= @eventos.count %>)</h3>
    <%= month_calendar events: @eventos do |date, eventos| %>
      <%= date.day %>
      <% eventos.each do |evento| %>
        <div class="evento">
          <% equipo = Equipo.find(evento.equipo_id) %>
          <% act = evento.tipoEvento == "Entrenamiento" ? "Ent" : "Jgo" %>
          <%= link_to "#{equipo.name}: #{act}", evento %>
        </div>
      <% end %>
    <% end %>
  <% else %>
    No permitido
  <% end %>
</div>

app/views/eventos/edit.html.erb
<% provide(:title, "Eventos") %>
<div class="container-fluid bg-2">
  <h4>Modificar eventos</h4>
  <%= render 'form' %>
</div>

app/views/eventos/evento_players.html.erb
<div class="container">
  <h3>Registro de asistencias</h3>
  <h4>Equipo: <%= @equipo.name %></h4>
  <%= form_for @evento do |f| %>

    <div>
      <%= @evento.tipoEvento %> <%= @evento.fecha %> <%= @evento.comment %>
    </div><br>
    <div class="row encabezado-asis">
      <p class="col-sm-4">Alumno</p>
      <p class="col-sm-4">Asistencia</p>
      <p class="col-sm-4">Comentarios</p>
    </div>

    <div class="container">

      <%= f.fields_for :asistencias do |asis| %>
        <div class="row reng-asis">

          <div class="col-sm-4">
            <% jugador = @jugadores.find_by(id:asis.object.player_id) %>

            <% puts "****************************" %>
            <% p jugador %>
            <% p asis.object %>
            <% puts "****************************" %>
            <%= jugador.apellidoPaterno %> <%= jugador.apellidoMaterno %>, <%= jugador.nombres %>
						<%= asis.hidden_field :player_id, :value => jugador.id %>
          </div>

          <div class="col-sm-4">

            <%= asis.select(:tipo, @tiposAsistencia) %>
          </div>

          <div class="col-sm-4">
            <%= asis.text_field :comment %>
          </div>
        </div>
      <% end %>
      <br>
      <div class="row">
      <% puts "============================" %>
      <% puts @evento.asistencias %>
      <% puts "============================" %>
      <%= f.hidden_field :registrado, :value => true %>
      <%= f.submit 'Registrar', class: "btn btn-default", style: "width: 20em; align: center;"  %>
      </div>
    </div>

  <% end %>
</div>

app/views/eventos/form_borrar.html.erb
<% provide(:title, "Entrenamientos") %>
<div class="col-sm-6 col-sm-offset-3">
  <p id="notice"><%= notice %></p>

  <h1>Eliminar Entrenamientos en lotes</h1>

  <%= form_tag(borrar_path) do %>
    <%= label_tag(:inicio, "Fecha inicial:") %>
    <%= date_field_tag :inicio, class: 'form-control' %>
    <%= label_tag(:final, "Fecha final:") %>
    <%= date_field_tag :final, class: 'form-control' %>
    <%= submit_tag "Eliminar eventos", class: "btn btn-default" %>
  <% end %>

</div>

app/views/eventos/forma_prog.html.erb
<% provide(:title, "Entrenamientos") %>
<div class="col-sm-6 col-sm-offset-3">
  <p id="notice"><%= notice %></p>

  <h1>Programación de Entrenamientos</h1>

  <%= form_tag(programa_path) do %>
    <% dias = [] %>
    <%= label_tag(:entrenador, "Entrenador:") %>
    <%= select_tag :entrenador, options_from_collection_for_select(@entrenadores, "id", "name"), prompt: "Seleccione el entrenador", class: 'form-control' %>
    <b>Dias:</b>
    <div class="well">
        <% @dias.each_with_index do |day, index| %>
          <%= label_tag day, day, class: "checkbox-inline nopadding"; %>
          <%= check_box_tag 'dias[]', index, checked = false, class: "nopadding" %>  |
        <% end %>
    </div>
    <%= label_tag(:inicio, "Fecha inicial:") %>
    <%= date_field_tag :inicio, class: 'form-control' %>
    <%= label_tag(:final, "Fecha final:") %>
    <%= date_field_tag :final, class: 'form-control' %>
    <%= submit_tag "Crear evento", class: "btn btn-default" %>
  <% end %>

</div>

app/views/eventos/index.html.erb
<% provide(:title, 'Eventos') %>
<h1>Listado de eventos</h1>

<%= link_to 'Crear evento', new_evento_path, class: "btn btn-default" %>

<%= will_paginate %>

<table>
  <thead>
    <tr>
      <th>Fecha</th>
      <th>Tipo</th>
      <th>Equipo</th>
      <th>Comentarios</th>
      <th colspan="3">Acciones</th>
    </tr>
  </thead>
  <tbody>
    <%= render @eventos %>
  </tbody>
</table>
<p>
  <%= link_to "CSV", eventos_path(format: "csv") %> |
  <%= link_to "Excel", eventos_path(format: "xls") %>
</p>
<%= will_paginate %>

app/views/eventos/index.xls.erb
<table>
  <thead>
    <tr>
      <th>Fecha</th>
      <th>Tipo de Evento</th>
      <th>Equipo</th>
      <th>Comentarios</th>
      <th>Registrado</th>
    </tr>
  </thead>
  <tbody>
    <% @eventos.each do |evento| %>
      <tr>
        <td><%= evento.fecha %></td>
        <td><%= evento.tipoEvento %></td>
        <td><%= Equipo.find_by(id: evento.equipo_id).name %></td>
        <td><%= evento.comment %></td>
        <td><%= evento.registrado %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/eventos/new.html.erb
<% provide(:title, "Eventos") %>
<div class="container-fluid bg-2">
  <h4>Evento nuevo</h4>
  <%= render 'form' %>
</div>

app/views/eventos/show.html.erb
<div class="col-sm-8">
    <h3>Equipo: <%= @equipo.name %></h3>
    <table class="eventos">
      <thead>
        <td><%= @evento.tipoEvento %></td>
        <td><%= @evento.fecha %></td>
        <td><%= @evento.comment %></td>
      </thead>
      <th>Jugador</th>
      <th>Registro</th>
      <th>Comentario</th>
      <tbody>
        <% @jugadores.each do |player| %>
          <tr>
            <td style="text-align: left;"><%= player.apellidoPaterno %></td>
            <% if asist = @evento.asistencias.find_by(player_id:player.id) %>
              <td><%= asist.tipo %></td>
              <td><%= asist.comment %></td>
            <% else %>
              <td colspan="3">Nuevo Ingreso</td>
            <% end %>

          </tr>
        <% end %>
      </tbody>
    </table>
</div>