config/routes.rb
Rails.application.routes.draw do
  resources :deportes do
    collection { post :import }
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/help/relations', to: 'static_pages#help_relations'
  get '/help/avatar', to: 'static_pages#help_avatar'
  get '/help/opciones', to: 'static_pages#help_opciones'
  get '/about', to: 'static_pages#about'
  get '/acceso', to: 'users#new'
  post '/acceso', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    collection { post :import }
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :categorias do
    collection { post :import }
  end
  get '/equipos/forma_rep'
  post '/equipos/reporte_asist', to: 'equipos#reporte_asist', as: 'reporte_asist'
  resources :players do
    collection { post :import }
  end
  get '/eventos/forma_prog' # Get programming parameters form
  get '/eventos/calendario' => 'eventos#calendario', as: 'calendario'
  post '/eventos/programa'   => 'eventos#programa',   as: 'programa'
  get '/eventos/form_borrar' # Get borrar parameters form
  post '/eventos/borrar'    =>'eventos#borra',   as: 'borrar'
  resources :eventos
  get '/equipos/:id/eventos_feed' => 'equipos#eventos_feed', as: 'eventosFeed'
  get '/eventos/:id/players_feed' => 'eventos#evento_players', as: 'eventoPlayers'
  # asistencias#new not required because Asistencia.new is called at
  # eventos#evento_players
  # get '/asistencias/new', to: 'asistencias#new'
  post '/asistencias', to: 'asistencias#create'
  get '/validar/:equipo_id', to: 'players#validar'
	resources :equipos do
	  collection { post :import }
	end
end

app/models/equipo.rb
class Equipo < ApplicationRecord
  belongs_to :user
  has_many :players
  has_many :eventos, dependent: :destroy
  validates :user_id, :name, presence: true

  def self.to_csv(options = {})
    desired_columns = ["id", "name", "categoria", "deporte", "rama", "user_id"]
    CSV.generate(options) do |csv|
      csv << desired_columns
      all.each do |equipo|
        csv << equipo.attributes.values_at(*desired_columns)
      end
    end
  end

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      equipo = find_by_id(row["id"]) || new
      equipo.attributes = row.to_hash
      equipo.save!
    end
  end

end

app/controllers/equipos_controller.rb
class EquiposController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :create, :destroy]
  before_action :set_equipo,    only: [:show, :edit, :update, :destroy, :eventos_feed]
  before_action :set_deportes,  only: [:new, :edit, :create]
  before_action :set_categorias, only: [:new, :show, :edit, :update, :create]
  before_action :set_ramas,      only: [:new, :show, :edit, :update, :create]

  # GET /equipos
  # GET /equipos.json
  def index
    @equipos = Equipo.paginate(page: params[:page])

    respond_to do |format|
      format.html
      format.csv { send_data @equipos.to_csv }
      format.xls
    end
  end

  # POST /equipos/import
  def import
    Equipo.import(params[:file])
    flash[:success] = 'Se ha importado exitosamente el archivo de equipos a la base de datos.'
    redirect_to equipos_path
  end

  # GET /equipos/1
  # GET /equipos/1.json
  def show
    @entrenador = User.find(@equipo.user_id)
    @categoria = Categoria.find(@equipo.categoria)
    @players = @equipo.players
  end

  # GET /equipos/new
  def new
    @equipo = Equipo.new
    @usuarios = User.all
  end

  # GET /equipos/1/edit
  def edit
    @usuarios = User.all
  end

  # POST /equipos
  # POST /equipos.json
  def create
    @equipo = Equipo.new(equipo_params)

    if @equipo.save
      flash[:success] = "Se ha registrado exitosamente el nuevo equipo."
      redirect_to equipos_path
    else
      render 'new'
    end
  end

  # PATCH/PUT /equipos/1
  # PATCH/PUT /equipos/1.json
  def update

    if @equipo.update(equipo_params)
      flash[:success] = 'Se actualizó exitosamente el equipo.'
      redirect_to equipos_path
    else
      render 'edit'
    end
  end

  # DELETE /equipos/1
  # DELETE /equipos/1.json
  def destroy
    # In order to guard Player dependency on Equipo and avoid the system to crash
    # Execute player.seguro for all players associated to this team first
    #
    safeTeam = Equipo.find_by(name: "99 - NO DETERMINADO")
    @equipo.players.each do |plyr|
      plyr.seguro safeTeam.id
    end

    @equipo.destroy
    flash[:success] = 'Se eliminó correctamente el equipo.'
    redirect_to equipos_url
  end

  # GET /equipos/1/eventos_feed
  def eventos_feed
    @feed_eventos = @equipo.eventos
  end

  # GET /equipos/forma_rep
  def forma_rep
    @equipo = Equipo.new
    @entrenadores = User.all
  end

  # PUT /equipos/reporte_asist
  def reporte_asist

    if params[:entrenador]
      @entrenador = User.find(params[:entrenador].to_i)
      @inicio = Time.parse(params[:inicio])
      @final = Time.parse(params[:final])
      @equipos = @entrenador.equipos
      @eventos = reporte(@entrenador.id, @inicio, @final)
    else
      @entrenador = current_user
      @equipos = @entrenador.equipos
      @equipos.each do |equi|
        @eventos << equi.eventos
      end
    end

    # Setup Vertical asistencias as horizontal for each evento
    # Creating a two dimensional array @reporte_rows indexed
    @reporte_rows = []
    # First row is type of events
    # Second row is evento dat
    first_row = ["Evento:"]
    second_row = ["Fecha:"]
    
    respond_to do |format|
      format.html
      format.xls
    end

  end

  private

  # Find correct set of eventos for user's teams
  def reporte entrena, inicio, final
    entrenador = User.find(entrena)
    equipos = entrenador.equipos

    @events = []
    equipos.each do |equipo|

      equipo.eventos.each do |event|

        if (event.fecha >= inicio) && (event.fecha <= final)
          @events << event
        end

      end
    end
    return @events
  end

  # Set @deportes to select from in form.
  def set_deportes
    @deportes = Deporte.all
    # @deportes = [ 'FUTBOL', 'HANDBALL', 'BASKETBOL', 'PORRA', 'TKD', 'SOFTBALL', 'BEISBOL', 'VOLEYBOL', 'TENIS DE MESA', 'BANDA DE GUERRA', 'NATACIÓN', 'BADMINGTON', 'GIMNASIA ARTÍSTICA', 'TOCHITO', 'AJEDRÉZ' ]
  end

  def set_ramas
    #@ramas = { 1 => 'Varonil', 2 => 'Femenil', 3 => 'Mixto' }
    @ramas = ['VARONIL', 'FEMENIL', 'MIXTO']
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_equipo
    @equipo = Equipo.find(params[:id])
  end

  def set_categorias
    @categorias = Categoria.all
  end

  def equipo_params
    params.require(:equipo).permit(:name, :categoria, :deporte, :rama, :user_id)
  end
end

app/helpers/equipos_helper.rb
module EquiposHelper
end

app/views/equipos/_eplayers.html.erb
<% secuencia = 1 %>
<% @players.each do |player| %>
  <tr id="player-<%= player.id %>">
    <td class="col-left"><%= secuencia %></td>
    <td class="col-left"><%= link_to player.nombres, player %></td>
    <td class="col-left"><%= player.apellidoPaterno %></td>
    <td class="col-left"><%= player.apellidoMaterno %></td>
    <% if current_user.admin? %>
      <% beca = player.beca ? "Si" : "No" %>
      <td class="col-left"><%= beca %></td>
      <td><%= link_to '', edit_player_path(player), class: "glyphicon glyphicon-edit" %></td>
      <td><%= link_to '', player, class: "glyphicon glyphicon-trash", method: :delete,
              data: { confirm: '¿Está seguro?' } %></td>
    <% end %>
  </tr>
  <% secuencia += 1 %>
<% end %>

app/views/equipos/_equipo.html.erb
<tr id="equipo-<%= equipo.id %>">
  <% if equipo.id != 1 %>
    <td class="col-left"><%= link_to equipo.name, equipo %></td>
    <td class="col-left"><%= Categoria.find(equipo.categoria).nombre %></td>
    <td class="col-left"><%= Deporte.find(equipo.deporte).nombre %></td>
    <td class="col-left"><%= equipo.rama %></td>
    <td class="col-left"><%= equipo.user.name %></td>
    <td><%= link_to '', edit_equipo_path(equipo), class: "glyphicon glyphicon-edit" %></td>
    <td><%= link_to '', equipo, class: "glyphicon glyphicon-trash", method: :delete,
        data: { confirm: '¿Está seguro?' } %></td>
  <% end %>
</tr>

app/views/equipos/_form.html.erb
<div class="col-sm-6 col-sm-offset-3">
  <%= form_for(@equipo) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <div class="field-tm">
      <%= f.label :name, "Equipo" %>
      <%= f.text_field :name, :placeholder => "Nombre del equipo", class: 'form-control' %>
    </div>
    <div>
      <%= f.label :categoria %>
      <%= f.collection_select( :categoria, @categorias, :id, :nombre, :placeholder => "Categoría del equipo", class: 'form-control') %>
    </div>
    <div>
      <%= f.label :deporte %>
      <%= f.collection_select( :deporte, @deportes, :id, :nombre, :placeholder => "Deporte que practica el equipo", class: 'form-control') %>
    </div>
    <div>
      <%= f.label :rama %>
      <%= f.select :rama, @ramas, :prompt => "Rama del equipo", class: 'form-control' %>
    </div>
    <div>
      <%= f.label :user_id, "Entrenador" %>
      <%= f.collection_select( :user_id, @usuarios, :id, :name, :placeholder => "Entrenador del equipo", class: 'form-control') %>
    </div>

    <%= f.submit "Guardar", class: "btn btn-default" %>
  <% end %>
</div>

app/views/equipos/edit.html.erb
<% provide(:title, "Equipos") %>
<div class="container-fluid bg-2">
  <h4>Modificar equipos</h4>
  <%= render 'form' %>
</div>

app/views/equipos/eventos_feed.html.erb
<div class="row">
  <aside class="col-xs-4">
    <section class="user_info">
      <%= render 'shared/user_info' %>
    </section>
  </aside>
  <div class="col-xs-8">
    <h3>Listado de eventos</h3>
    <table>
      <thead>
        <th colspan="4">
          <%= @equipo.name %>
        </th>
        <tr>
          <th>Activar</th>
          <th>Fecha</th>
          <th>Tipo</th>
          <th>Comentarios</th>
        </tr>
      </thead>
      <tbody>

        <% @feed_eventos.each do |evento| %>

          <% puts "**********************************" %>
          <% puts "**  Evento ID:    #{evento.id}  " %>
					<% puts "**  Evento: #{evento}" %>
          <% puts "**********************************" %>
          <tr id="evento-<%= evento.id %>">
						<% if evento.registrado %>
							<td class="eve-accion"><%= link_to '', evento_path(evento.id),
																					class: "glyphicon glyphicon-eye-open", data: { equipo: @equipo } %></td>
						<% else %>
            	<td class="eve-accion"><%= link_to '', eventoPlayers_path(evento.id),
                              class: "glyphicon glyphicon-off", data: { equipo: @equipo } %></td>
						<% end %>
            <td class="eve-fecha"><%= evento.fecha.to_date %></td>
            <td class="eve-tipo"><%= evento.tipoEvento %></td>
            <td class="eve-comment"><%= evento.comment %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
</div>
<div class="row">

</div>

app/views/equipos/forma_rep.html.erb
<% provide(:title, "Reporte Asistencias") %>
<div class="col-sm-6 col-sm-offset-3">
  <p id="notice"><%= notice %></p>

  <h1>Reporte de Asistencias</h1>

  <%= form_tag(reporte_asist_path) do %>
    <%= label_tag(:entrenador, "Entrenador:") %>
    <%= select_tag :entrenador, options_from_collection_for_select(@entrenadores, "id", "name"), prompt: "Seleccione el entrenador", class: 'form-control' %>
    <%= label_tag(:inicio, "Fecha inicial de reporte:") %>
    <%= date_field_tag :inicio, class: 'form-control' %>
    <%= label_tag(:final, "Fecha final de reporte:") %>
    <%= date_field_tag :final, class: 'form-control' %>
    <%= submit_tag "Crear Reporte", class: "btn btn-default" %>
  <% end %>

</div>

app/views/equipos/index.html.erb
<% provide(:title, 'Listado de equipos') %>

<div class="row">
  <h1>Listado de equipos</h1>

  <%= link_to 'Crear equipo', new_equipo_path, class: "btn btn-default" %>

  <%= will_paginate %>

  <table>
    <thead>
      <tr>
        <th>Equipo</th>
        <th>Categoría</th>
        <th>Deporte</th>
        <th>Rama</th>
        <th>Entrenador</th>
        <th colspan="3">Acciones</th>
      </tr>
    </thead>
    <tbody>
      <%= render @equipos %>
    </tbody>
  </table>
  <p>
    Exportar
    <%= link_to "CSV", equipos_path(format: "csv") %> |
    <%= link_to "Excel", equipos_path(format: "xls") %>
  </p>
  <%= will_paginate %>

  <span class="navbar-left">
    <h4>Importar equipos (CSV)</h4>

    <%= form_tag import_equipos_path, multipart: true, class: "navbar-form navbar-left search-form" do %>
      <%= file_field_tag :file, class: "form-control" %>
      <%= submit_tag "Importar equipos", class: "btn btn-default" %>
    <% end %>
  </span>
</div>

app/views/equipos/index.xls.erb
<meta http-equiv="content-type" content="text/html;charset=UTF-8" />
<table>
  <thead>
    <tr>
      <th>Equipo</th>
      <th>Categoría</th>
      <th>Deporte</th>
      <th>Rama</th>
      <th>Entrenador</th>
    </tr>
  </thead>
  <tbody>
    <% @equipos.each do |equipo| %>
      <tr>
        <td><%= equipo.name %></td>
        <td><%= Categoria.find_by(id: equipo.categoria).nombre %></td>
        <td><%= equipo.deporte %></td>
        <td><%= equipo.rama %></td>
        <td><%= equipo.user.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/equipos/new.html.erb
<%= provide(:title, "Equipos") %>
<div class="container-fluid bg-2">
  <h4>Equipo nuevo</h4>
  <%= render 'form' %>
</div>

app/views/equipos/reporte_asist.html.erb
<% provide(:title, "Reporte Asistencias") %>
<div class="bg-2 container-fluid">
  <p id="notice"><%= notice %></p>

  <h1>Reporte de Asistencias</h1>
  <h3>Entrenador: <%= @entrenador.name %></h3>
  <table class="col-sm-6">
    <thead>
      
    </thead>
    <tbody>
      <% @equipos.each do |equipo| %>
        <tr class="repor_equipo">
          <th>Equipo:</th>
          <th colspan="2"><%= equipo.name %></th>
        </tr>
        <% @eventos.each do |even| %>

          <% if even.equipo_id == equipo.id %>
            <tr class="repor_evento">
              <th>Evento:</th>
              <th><%= even.tipoEvento %></th>
              <th>(<%= even.fecha %>)</th>
            </tr>
            <% even.asistencias.each do |asist| %>
              <tr>
                <td style="text-align:left;"><%= asist.player.apellidoPaterno %> <%= asist.player.apellidoMaterno %>, <%= asist.player.nombres %> </td>
                <td><%= asist.tipo %></td>
                <td><%= asist.comment %></td>
              </tr>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>

  </table>
  <div data-no-turbolinks>
    <%= link_to "Excel", reporte_asist_url(format: "xls", entrenador: @entrenador.id, inicio: @inicio, final: @final, controller: "equipos", action: "reporte_asist"), method: :post  %>
  </div>

</div>

app/views/equipos/reporte_asist.xls.erb
<meta http-equiv="content-type" content="text/html;charset=UTF-8" />
<table>
      <tr>
        <td>Entrenador:</td>
        <td><%= @entrenador.name %></td>
      </tr>
  <% @equipos.each do |equipo| %>
      <tr style="font-size:1.2em;">
        <td>Equipo:</td>
        <td><%= equipo.name %></td>
      </tr>
    <% @eventos.each do |even| %>
      <% if even.equipo_id == equipo.id %>
      <tr style="font-size:1.2em;">
        <td>Evento:</td>
        <td><%= even.tipoEvento %></td>
        <td><%= even.fecha %></td>
      </tr>
        <% even.asistencias.each do |asist| %>
      <tr>
        <td><%= asist.player.apellidoPaterno %></td>
        <td><%= asist.player.apellidoMaterno %></td>
        <td><%= asist.player.nombres %></td>
        <td><%= asist.tipo %></td>
        <td><%= asist.comment %></td>
      </tr>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
</table>

app/views/equipos/show.html.erb
<% provide(:title, "Equipos") %>
<div class="container-fluid bg-2">
  <section class="col-sm-8">


  <p id="notice">
    <%= notice %>
  </p>

  <h4>Equipo: <b><%= @equipo.name %></b></h4>
  <table>
    <tbody>
      <tr>
        <td class="col-left">Categoría:</td>
        <td class="col-left"><%= @categoria.nombre %></td>
      </tr>
      <tr>
        <td class="col-left">Deporte:</td>
        <td class="col-left"><%= Deporte.find(@equipo.deporte).nombre %></td>
      </tr>
      <tr>
        <td class="col-left">Rama:</td>
        <td class="col-left"><%= @equipo.rama %></td>
      </tr>
      <tr>
        <td class="col-left">Entrenador:</td>
        <td class="col-left"><%= @entrenador.name %></td>
      </tr>
    </tbody>
  </table>
  <% if current_user.admin? %>
    <%= link_to '', edit_equipo_path(@equipo), class: "glyphicon glyphicon-edit" %>
    <%= link_to '', @equipo, class: "glyphicon glyphicon-trash", method: :delete,
        data: { confirm: '¿Está seguro?' } %>
  <% end %>
  <br><h5>Listado de Jugadores</h5>
  <table>
    <thead>
      <tr>
        <th>Sec.</th>
        <th>Nombres</th>
        <th>Apellido paterno</th>
        <th>Apellido materno</th>
        <% if current_user.admin? %>
          <th>Beca</th>
          <th colspan="3">Acciones</th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <%= render 'eplayers' %>
    </tbody>
  </table>

  </section>
</div>