config/routes.rb
Rails.application.routes.draw do
  resources :deportes do
    collection { post :import }
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/help/relations', to: 'static_pages#help_relations'
  get '/help/avatar', to: 'static_pages#help_avatar'
  get '/help/opciones', to: 'static_pages#help_opciones'
  get '/about', to: 'static_pages#about'
  get '/acceso', to: 'users#new'
  post '/acceso', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    collection { post :import }
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :categorias do
    collection { post :import }
  end
  get '/equipos/forma_rep'
  post '/equipos/reporte_asist', to: 'equipos#reporte_asist', as: 'reporte_asist'
  resources :players do
    collection { post :import }
  end
  get '/eventos/forma_prog' # Get programming parameters form
  get '/eventos/calendario' => 'eventos#calendario', as: 'calendario'
  post '/eventos/programa'   => 'eventos#programa',   as: 'programa'
  get '/eventos/form_borrar' # Get borrar parameters form
  post '/eventos/borrar'    =>'eventos#borra',   as: 'borrar'
  resources :eventos
  get '/equipos/:id/eventos_feed' => 'equipos#eventos_feed', as: 'eventosFeed'
  get '/eventos/:id/players_feed' => 'eventos#evento_players', as: 'eventoPlayers'
  # asistencias#new not required because Asistencia.new is called at
  # eventos#evento_players
  # get '/asistencias/new', to: 'asistencias#new'
  post '/asistencias', to: 'asistencias#create'
  get '/validar/:equipo_id', to: 'players#validar'
	resources :equipos do
	  collection { post :import }
	end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Fernando Flores | <%= $luis.email %> | <%= $luis.web %>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Autor", about_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <%= link_to image_tag("logo.png", alt: "ECA", size: "50"), 'http://www.eca.edu.mx/', id: "logo" %>
    </div>

      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Inicio",  root_path %></li>
        <li><%= link_to "Ayuda",   help_path %></li>
        <% if logged_in? %>
          <% if current_user.admin? %>
            <li><%= link_to "Usuarios", users_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Mantenimiento <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Deportes", deportes_path %></li>
                <li><%= link_to "Categorías", categorias_path %></li>
                <li><%= link_to "Equipos", equipos_path %></li>
                <li><%= link_to "Jugadores", players_path %></li>
                <li><%= link_to "Eventos", eventos_path %></li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Herramientas <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Calendario", calendario_path %></li>
                <li><%= link_to "Reporte", equipos_forma_rep_path %></li>
                <li><%= link_to "Programación", eventos_forma_prog_path %></li>
                <li><%= link_to "Borrar eventos", eventos_form_borrar_path %></li>
              </ul>
            </li>
          <% end %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Cuenta <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Perfil", current_user %></li>
              <li><%= link_to "Modificar datos", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Salir de sesión", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Iniciar sesion", login_path %></li>
        <% end %>
      </ul>

  </div>
</header>

app/views/layouts/_leftSide.html.erb
<aside class="col-sm-4">
  <section class="user_info">
    <%= yield %>
  </section>
</aside>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>